sudo: true

language: php

php:
  - 7.1.9

cache:
  directories:
    - vendor
    - "$HOME/.composer/cache"

script:
  - composer install

after_script:
  - chmod 600 ./key
  - rsync -r /home/travis/build/xiaodit/think-admin/* -e "ssh -o StrictHostKeyChecking=no -i ./key -p ${XDPORT}" ${XDUSER}@${XDHOST}:${XDPATH}
